### ISSUE TITLE
Grade 1 - Explosions!

### ISSUE THREAD

**Issue by l2lam** [l2lam/Word-guessing-game-demo#18]
We recently learned that Grade 1's by-and-large love explosions.  Let's give it to them: as a reward for completing a puzzle, show/animate explosions, proportional to the score (perhaps in steps... from small puffs to nuclear mushrooms).

**Comment by SAOfan** [comment]
maybe have it not be proportional to the score seeing as with some levels the player will end up with a lesser total score than in others for example assuming for both your score is rolled at 100 the word cat will only get you 300 points while a word like python will get you 600 points so instead it might make more sense if the explosions are proportional to what level the player is on instead of the score
